#!/usr/bin/perl -w
#
# count the number of tab-delimited columns.  Gives you 0-based result.
#

if ((defined $ARGV[0]) && (($ARGV[0] eq '-h') || ($ARGV[0] eq '--help'))) {
  print "Usage: ncols.pl [ -d DELIMITER ] [ -n # ] [ -l ] INPUT\n";
  print "Counts number of columns, gives 0-based result.\n";
  print "  -d specifies delimiter, default is tab.\n";
  print "  -n specifies number of lines from INPUT to count, default is 1.\n";
  print "  -l specifies list mode, where column data is printed with the column number.\n       Default is not list mode.\n";
  exit (-1);
}

use Getopt::Long;
&Getopt::Long::Configure("pass_through");
$delimiter = "\t";
$numlines = 1;
$list = 0;
GetOptions ('d=s' => \$delimiter,
            'n=i' => \$numlines,
            'l' => \$list);

$i = 0;
while (defined ($in = <>)) {
  chomp $in;
  @in = split /$delimiter/, $in;
  if ($list) {
    foreach $j (0..$#in) { print "$j\t$in[$j]\n"; }
  }
  else { print "$#in\n"; }
  ++$i;
  last if ($i == $numlines);
}
